export const tableColumns = [
  { label: '序号', type: 'index' },
  { type: 'selection' },
  { label: '业务环节', prop: '业务环节' },
  { label: '医保经办部门', prop: '医保经办部门' },
  { label: '业务交接号', prop: '业务交接号' },
  { label: '医院编码', prop: '医院编码' },
  { label: '医院名称', prop: '医院名称' },
  { label: '申报起始日期', prop: '申报起始日期' },
  { label: '申报终止日期', prop: '申报终止日期' },
  { label: '就医人数合计', prop: '就医人数合计' },
  { label: '就医人次合计', prop: '就医人次合计' },
  { label: '医疗费用总额合计(元)', prop: '医疗费用总额合计(元)' },
  { label: '个人自负金额合计(元)', prop: '个人自负金额合计(元)' },
  { label: '记账金额合计(元)', prop: '记账金额合计(元)' },
  { label: '申报单据数', prop: '申报单据数' },
  { label: '申报说明', prop: '申报说明' },
  { label: '申报人', prop: '申报人' },
  { label: '申报日期', prop: '申报日期' },
  { label: '受理说明', prop: '受理说明' },
  { label: '受理人', prop: '受理人' },
  { label: '受理时间', prop: '受理时间' },
  { type: 'operation', label: '操作', fixed: 'right', width: '160px' }
]

