export default [
  { type: 'index', label: '序号', width: '55px' },
  { prop: 'nameCode', label: '登账明细ID' },
  { prop: 'name', label: '登账事件ID' },
  { prop: 'code', label: '会计区间' },
  { prop: 'code', label: '清单汇总号' },
  { prop: 'nameCode', label: '凭证流水号' },
  { prop: 'code', label: '银行首付报盘序列号' },
  { prop: 'nameCode', label: '合并账套' },
  { prop: 'nameCode', label: '收支类型' },
  { prop: 'nameCode', label: '记账凭证种类' },
  { prop: 'nameCode', label: '登账类型' },
  { prop: 'nameCode', label: '财务实收/付款方式' },
  { prop: 'nameCode', label: '财务科目代码' },
  { prop: 'nameCode', label: '当事人类别' },
  { prop: 'nameCode', label: '当事人ID' },
  { prop: 'nameCode', label: '对方开户银行编号' },
  { prop: 'nameCode', label: '对方开户银行户名' },
  { prop: 'nameCode', label: '对方开户银行账号' },
  { prop: 'nameCode', label: '借贷方向' },
  { prop: 'nameCode', label: '金额（元）' },
  { prop: 'nameCode', label: '日记账收入金额（元）' },
  { prop: 'nameCode', label: '日记账支出金额（元）' },
  { prop: 'nameCode', label: '银行记账日期型' },
  { prop: 'nameCode', label: '财务记账日期型' },
  { prop: 'nameCode', label: '附件张数' },
  { prop: 'nameCode', label: '摘要' },
  { prop: 'nameCode', label: '经办人' },
  { prop: 'nameCode', label: '经办时间' },
  { prop: 'nameCode', label: '经办机构' }
]
