export const medicalColumns = [
  { type: 'selection' },
  { type: 'index', label: '序号' },
  { label: '就医地所属省', prop: '就医地所属省' },
  { label: '就医地所属市', prop: '就医地所属市' },
  { label: '就医地所属区县', prop: '就医地所属区县' },
  { label: '医疗机构编码', prop: '医疗机构编码' },
  { label: '医疗机构名称', prop: '医疗机构名称' },
  { label: '清分年月', prop: '清分年月' },
  { label: '业务类型', prop: '业务类型' },
  { label: '就医人次', prop: '就医人次' },
  { label: '就医人数', prop: '就医人数' },
  { label: '总费用(元)', prop: '总费用(元)' },
  { label: '个人支付费用(元)', prop: '个人支付费用(元)' },
  { label: '记账费用(元)', prop: '记账费用(元)' },
  { label: '审核扣减费用(元)', prop: '审核扣减费用(元)' },
  { label: '预付金实际支付费用(元)', prop: '预付金实际支付费用(元)' },
  { label: '确认标志', prop: '确认标志' },
  { label: '备注', prop: '备注' }
]

export const medicalDetailColumns = [
  { type: 'selection' },
  { type: 'index', label: '序号' },
  { label: '比对结果', prop: '比对结果' },
  { label: '就医地所属省', prop: '就医地所属省' },
  { label: '就医地所属市', prop: '就医地所属市' },
  { label: '就医地所属区县', prop: '就医地所属区县' },
  { label: '医疗机构编码', prop: '医疗机构编码' },
  { label: '医疗机构名称', prop: '医疗机构名称' },
  { label: '清分年月', prop: '清分年月' },
  { label: '业务类型', prop: '业务类型' },
  { label: '就诊记录号', prop: '就诊记录号' },
  { label: '身份证号', prop: '身份证号' },
  { label: '姓名', prop: '姓名' },
  { label: '性别', prop: '性别' },
  { label: '异地就医类型', prop: '异地就医类型' },
  { label: '入院日期', prop: '入院日期' },
  { label: '出院日期', prop: '出院日期' },
  { label: '结算日期', prop: '结算日期' },
  { label: '总费用(元)', prop: '总费用(元)' },
  { label: '个人支付费用(元)', prop: '个人支付费用(元)' },
  { label: '记账费用(元)', prop: '记账费用(元)' },
  { label: '审核扣减费用(元)', prop: '审核扣减费用(元)' },
  { label: '预付金实际支付费用(元)', prop: '预付金实际支付费用(元)' },
  { label: '自费费用(元)', prop: '自费费用(元)' },
  { label: '个人自付费用(元)', prop: '个人自付费用(元)' },
  { label: '备注', prop: '备注' },
  { type: 'operation', label: '操作', fixed: 'right', width: '100px' }
]

export const deductionColumns = [
  { type: 'selection' },
  { type: 'index', label: '序号' },
  { label: '费用明细流水号', prop: '费用明细流水号' },
  { label: '医疗机构三大目录编码', prop: '医疗机构三大目录编码' },
  { label: '医疗机构三大目录名称', prop: '医疗机构三大目录名称' },
  { label: '本条费用明细扣款金额(元)', prop: '本条费用明细扣款金额(元)' },
  { label: '医疗费用扣款原因', prop: '医疗费用扣款原因' },
  { label: '就诊记录号(本地)', prop: '就诊记录号(本地)' },
  { label: '医院编码', prop: '医院编码' },
  { label: '备注', prop: '备注' },
  { label: '经办人', prop: '经办人' },
  { label: '经办时间', prop: '经办时间' }
]
