export default [
  { type: 'index', label: '序号', width: '55px' },
  { prop: 'nameCode', label: '社保经办机构' },
  { prop: 'name', label: '征集通知流水号' },
  { prop: 'code', label: '电子税票号码缴费凭证号' },
  { prop: 'code', label: '险种类型' },
  { prop: 'nameCode', label: '单位编号' },
  { prop: 'nameCode', label: '缴费类型' },
  { prop: 'nameCode', label: '缴费人数' },
  { prop: 'nameCode', label: '职工工资总额(元)' },
  { prop: 'nameCode', label: '个人缴费基数总额（元）' },
  { prop: 'nameCode', label: '对应费款所属期' },
  { prop: 'nameCode', label: '单位缴费比例或定额标准' },
  { prop: 'nameCode', label: '单位实缴金额（元）' },
  { prop: 'nameCode', label: '个人缴费比例或定额标准' },
  { prop: 'nameCode', label: '个人实缴金额' },
  { prop: 'nameCode', label: '利息' },
  { prop: 'nameCode', label: '滞纳金' },
  { prop: 'nameCode', label: '缴费标识' },
  { prop: 'nameCode', label: '上解时间' },
  { prop: 'nameCode', label: '入国库时间' },
  { prop: 'nameCode', label: '主管税务部门代码' },
  { prop: 'nameCode', label: '数据传输类型' },
  { prop: 'nameCode', label: '传输批次号' },
  { prop: 'nameCode', label: '传输时间戳' }
]
