export default [
  { type: 'index', label: '序号', width: '55px' },
  { prop: 'nameCode', label: '预产期' },
  { prop: 'name', label: '取环日期' },
  { prop: 'code', label: '业务登记日期' },
  { prop: 'code', label: '一孩登记/在生育日期' },
  { prop: 'nameCode', label: '子女计划出生日期' },
  { prop: 'nameCode', label: '业务更新人' },
  { prop: 'nameCode', label: '人口标识ID' },
  { prop: 'name', label: '唯一标识' },
  { prop: 'code', label: '申请再生育理由' },
  { prop: 'code', label: '审批经办人' },
  { prop: 'nameCode', label: '业务更新地' },
  { prop: 'nameCode', label: '发证日期' },
  { prop: 'nameCode', label: '登记意见/审核结果' },
  { prop: 'nameCode', label: '业务登记地' },
  { prop: 'nameCode', label: '业务更新日期' },
  { prop: 'name', label: '申请书编号' },
  { prop: 'code', label: '审批日期' },
  { prop: 'code', label: '申请孩次' },
  { prop: 'nameCode', label: '业务登记人' },
  { prop: 'nameCode', label: '生育合同编码' },
  { type: 'nameCode', label: '生育合同签署日期' }
]
