export default [
  { type: 'index', label: '序号', width: '55px' },
  { prop: 'nameCode', label: '结婚登记申请号' },
  { prop: 'name', label: '男姓名' },
  { prop: 'code', label: '男身份证件类型' },
  { prop: 'code', label: '男身份证件号码' },
  { prop: 'nameCode', label: '男出生日期' },
  { prop: 'nameCode', label: '男国籍' },
  { prop: 'nameCode', label: '男民族' },
  { prop: 'name', label: '男文化程度' },
  { prop: 'code', label: '男职业' },
  { prop: 'code', label: '男联系电话' },
  { prop: 'nameCode', label: '男婚姻状况' },
  { prop: 'nameCode', label: '男户籍地省市县（区）' },
  { prop: 'nameCode', label: '男户籍地乡镇街道' },
  { prop: 'nameCode', label: '女姓名' },
  { prop: 'nameCode', label: '女身份证件类型' },
  { prop: 'code', label: '女身份证件号码' },
  { prop: 'nameCode', label: '女出生日期' },
  { prop: 'nameCode', label: '女国籍' },
  { prop: 'nameCode', label: '女民族' },
  { prop: 'name', label: '女文化程度' },
  { prop: 'code', label: '女职业' },
  { prop: 'code', label: '女联系电话' },
  { prop: 'nameCode', label: '女婚姻状况' },
  { prop: 'nameCode', label: '女户籍地省市县（区）' },
  { prop: 'nameCode', label: '女户籍地乡镇街道' },
  { prop: 'name', label: '血亲关系' },
  { prop: 'code', label: '复婚标志' },
  { prop: 'code', label: '结婚登记日期' },
  { prop: 'nameCode', label: '承办机关名称' },
  { prop: 'nameCode', label: '承办机关行政区划' }
]
