export default [
  { type: 'selection' },
  { type: 'index', label: '序号', width: '55px' },
  { prop: 'nameCode', label: '绑定状态' },
  { prop: 'code', label: '开始时间' },
  { prop: 'code', label: '终止时间' },
  { prop: 'nameCode', label: '授权人证件类型' },
  { prop: 'nameCode', label: '授权人证件号码' },
  { prop: 'nameCode', label: '授权人姓名' },
  { prop: 'nameCode', label: '授权人性别' },
  { prop: 'nameCode', label: '授权人类别' },
  { prop: 'nameCode', label: '授权人单位名称' },
  { prop: 'nameCode', label: '授权人医保区划' },
  { prop: 'nameCode', label: '授权人账户余额（元）' },
  { prop: 'nameCode', label: '代理人证件类型' },
  { prop: 'nameCode', label: '代理人证件号码' },
  { prop: 'nameCode', label: '代理人联系方式' },
  { prop: 'nameCode', label: '代理人联系地址' },
  { prop: 'nameCode', label: '使用人人员编号' },
  { prop: 'nameCode', label: '使用人证件类型' },
  { prop: 'nameCode', label: '使用人姓名' },
  { prop: 'nameCode', label: '使用人性别' },
  { prop: 'nameCode', label: '使用人人员类别' },
  { prop: 'nameCode', label: '使用人医保区划' },
  { prop: 'nameCode', label: '与授权人关系' },
  { prop: 'nameCode', label: '申请人' },
  { prop: 'nameCode', label: '申请时间' },
  { prop: 'nameCode', label: '审核标志' },
  { prop: 'nameCode', label: '审核人' },
  { prop: 'nameCode', label: '审核时间' },
  { prop: 'nameCode', label: '审核意见' }
  // { type: 'operation', label: '操作', fixed: 'right', width: '100px' }
]
